// Auto-generated by scripts/bundle.sh — do not edit manually
enum BuildInfo {
    static let version = "0.9.5"
    static let gitHash = "af5456e"
    static let gitDate = "2026-05-01 13:42:50 +0200"
    static let gitMessage = "chore: bump version to 0.9.4"
    static let buildDate = "2026-05-14 20:38"
}
