// Auto-generated by scripts/bundle.sh — do not edit manually
enum BuildInfo {
    static let version = "1.1.0"
    static let gitHash = "391a00e"
    static let gitDate = "2026-06-21 15:33:09 +0200"
    static let gitMessage = "fix(cost): parse JSONL timestamps without fractional seconds"
    static let buildDate = "2026-06-21 16:46"
}
