// Auto-generated by scripts/bundle.sh — do not edit manually
enum BuildInfo {
    static let version = "1.1.1"
    static let gitHash = "5f15e0d"
    static let gitDate = "2026-06-30 12:55:54 +0200"
    static let gitMessage = "Preflight sandbox at session launch with actionable hint (#37)"
    static let buildDate = "2026-06-30 13:05"
}
